---
- name: Instalar e configurar o ContainerD
  hosts: all
  tasks:
  - name: Instalação dos módulos do Kernel Linux
    become: true
    ansible.builtin.copy:
      src: ./k8s.conf
      dest: /etc/modules-load.d/k8s.conf
      mode: '644'
      
  - name: Adicionando o overlay
    become: true
    modprobe:
      name: overlay
      state: present

  - name: Adicionando o br_netfilter
    become: true
    modprobe:
      name: br_netfilter
      state: present  
  
  - name: Configuração dos parametros do sysctl
    become: true
    ansible.builtin.copy:
      src: ./k8s-cri.conf
      dest: /etc/sysctl.d/k8s.conf
      mode: '644'
  
  - name: Executando o comando sysctl para implementas as configurações
    become: true
    command: "sysctl --system"

  - name: Desabilitando swap
    command: sudo swapoff -a 
    
  - name: Adicionar a chave do repositorio APT
    become: true
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg  
      state: present

  - name: Adicionando o repositorio para instalar ContainerD
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Instalando o ContainerD
    become: true
    apt: 
      name: containerd.io=1.6.18-1 
      update_cache: yes

  - name: Criação do diretório de configuração do ContainerD
    become: true
    file:
      path: /etc/containerd
      state: directory
      owner: root
      group: root
      mode: 0644

  - name: Cirar o arquivo de configuração
    become: true
    shell: containerd config default > /etc/containerd/config.toml
  
  - name: Trocando o config do containerd
    become: true
    command: sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

  - name: Restart ContainerD
    become: true
    ansible.builtin.service:
      name: containerd
      state: restarted

- name: Instalação do Kubeadm, KUbelet e do Kubectl
  hosts: all
  tasks:
    - name: Instalação dos pacotes requesitos
      become: true
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        state: present

    - name: Adicionando a chave do repositorio
      become: true
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present 
 
    - name: Adicionando o repositorio
      become: true
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present 

    - name: Instalação dos pacote Kubelet, Kubead e Kubectl
      become: true
      apt:
        pkg:
        - kubectl=1.26.0-00
        - kubeadm=1.26.0-00
        - kubelet=1.26.0-00    
        state: present
        update_cache: yes


- name: Inicio do Cluster k8s
  hosts: control_plane
  tasks:
    - name: Comando de Inicialização
      command: kubeadm init
      become: true
      ignore_errors: true

    - name: Criação do diretório .Kube  
      #become: true    
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755


    - name: Copia do arquivo kube config
      become: true
      ansible.builtin.copy:
        dest: /home/ubuntu/.kube/config
        src: /etc/kubernetes/admin.conf
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: 0640


    - name: Download foo.conf
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
        dest: /home/ubuntu
        mode: '0440'
    
    
#    - name: Baixando calico.yaml
#      command: wget https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml

    - name: Habilitando calico CIDR
      command: sed -i 's/# - name:\ CALICO_IPV4POOL_CIDR/- name:\ CALICO_IPV4POOL_CIDR/g' calico.yaml 

    - name: Alterando range de IP para o utilizado na rede atual
      command: sed -i 's/#\s*value:\s*"192\.168\.0\.0\/16"/  value:\ "172.16.0.0\/16"/g' calico.yaml
 
    - name: Aplicar a instalação do Calico
      command: kubectl apply -f /home/ubuntu/calico.yaml